export enum StatisticsFieldsName {
  numberWorkingDays = 'numberWorkingDays',
  numberDaysOff = 'numberDaysOff',
  numberVacationDays = 'numberVacationDays',
  numberSickDays = 'numberSickDays',
  numberAdditionalWorkingDays = 'numberAdditionalWorkingDays',
  numberWorkingHours = 'numberWorkingHours',
  numberFreeHours = 'numberFreeHours',
  numberVacationHours = 'numberVacationHours',
  numberSickHours = 'numberSickHours',
  numberAdditionalWorkingHours = 'numberAdditionalWorkingHours',
  totalDays = 'totalDays',
  totalHours = 'totalHours',
  numberFirstShifts = 'numberFirstShifts',
  numberSecondShifts = 'numberSecondShifts',
  numberNightHours = 'numberNightHours',
  grossAmountMoneyForWorkingDays = 'grossAmountMoneyForWorkingDays',
  nettoAmountMoneyForWorkingDays = 'nettoAmountMoneyForWorkingDays',
  grossAmountMoneyForVacationDays = 'grossAmountMoneyForVacationDays',
  nettoAmountMoneyForVacationDays = 'nettoAmountMoneyForVacationDays',
  grossAmountMoneyForSickDays = 'grossAmountMoneyForSickDays',
  nettoAmountMoneyForSickDays = 'nettoAmountMoneyForSickDays',
  totalMoneyEarnedGross = 'totalMoneyEarnedGross',
  totalMoneyEarnedNetto = 'totalMoneyEarnedNetto',
  totalTaxPaid = 'totalTaxPaid',
}
